### ISSUE TITLE
Vikunja Feedback

### ISSUE THREAD

**Issue by kolaente** [tborychowski/self-hosted-cookbook#4]
Hey there, creator of Vikunja here 

I couldn't help but notice the comment you put together on your [guide of Vikunja](https://github.com/tborychowski/self-hosted-cookbook/blob/master/apps/project-mgmt/vikunja.md) about "poor and messy UI". While I agree about the statement per se, what exactly didn't you like? Or was it more of the overall look and feel of it? How could I improve that?

(Also sorry for just opening an issue here, that was just the easiest way I found. If you want we can continue this conversation over email (konrad@vikunja.io) or some other tool)

**Comment by tborychowski** [comment]
Hi,

No problem, that is a good way to have a discussion on that.

Firstly, please bear in mind that this repo contains my own "database" of apps (which I moved to github from my personal wiki), so these comments are only my personal PoV and aimed at (primarily) myself. I didn't want to offend or criticise anyone, it's just - mainly - my personal preference. I'm also not a designer (albeit have been working in UI/UX dev for the past 20yrs), so I'll keep my comments & remarks below to the point and without a "personal preference" or "feeling" (like a designer might give you), as usage of a particular colour palette, animations, layouts or typography usually depends a lot on the person designing them. I'll focus on the usability, accessibility and general UX best practices.

Secondly, Vikunja looks like a great app, and I see that a lot of work has been put into it, as the functionality is quite extensive with a lot of potential for greatness.

I haven't done a proper UX review of your app when I wrote this comment. It was more a "general feel" of it. 
I did a quick review now (using your try.vikunja.io site).
So here it is:

1. Too many llamas! (sorry, I like the idea and the animal, but it shows up in the logo, and appears when toggling the sidebar, and it's taking the attention out of the interface
2. Usage of colours is "aggressive" at times, but most importantly very inconsistent, e.g. 
    - "Create namespace" screen changes the whole bg colour to laser-purple). That's not something you'd see in this type of an application (maybe more in music/video or other game-like apps, here it just looks unprofessional).
    - Highlight colour in menus & controls is different everywhere: 
        - sidebar: #fff, 
        - user drop-down: #f5f5f5, 
        - calendar control: #e6e6e6
    - some buttons are blue, some are green, (without denoting primary & secondary relationship), while others are material-design-type (dreadful) - i.e. no border or background, just underline (e.g. "Edit"), and others are just action-links (where a button would work much better) - see screenshot below for different button types found in the app.
    - The contrast ration in some parts if the UI is very low (especially highlighted elements background is not different enough from the non-highlighted background).
3. Same is with animation - some elements animate (e.g. sidebar), others just show up/disappear without the animation (either is fine, but should be used consistently)
4. Inconsistent use of components/elements:
    - Create new namespace (btw. "new" is redundant, you cannot create "old" namespace, because it already exists ;-)) - is a green button, while create a list is a plus icon.  One idea would be to put the "Namespaces" as a last item (in the sidebar) and show the "Plus" icon there - to create the namespace?
5. Alignment - things are not aligned, icons & text:
![Bitmap2](https://user-images.githubusercontent.com/392513/103424621-4688f580-4ba5-11eb-85a0-76147d587a6c.png)


I'd also have some notes on the general UX of this app:
- Namespaces idea is fine, albeit maybe it should not be enforced so much (i.e. I wanna just create some tasks, I don't want to learn about namespaces, teams, etc), or at least made clearer to the user that they can't create any tasks before creating a namespace and then a list in this namespace. When I start the app with no data - I land on the overview page and see "Nothing to do - Have a nice day!", with no buttons or info what to do next...
- e.g. List edit screen is probably the most confusing: 
    - starts with a huge cog icon next to the list name    
    - some actions require "Save" button, while others don't - so "Save" button is somewhere in the middle of the long form...
    - It's showing elements, that have no data (Share links table only shows table headers, when it's not shared which looks odd)
- Some actions (like creating a list, removing a namespace) are not applied without reloading the browser (bug?) which is confusing


### button variations
![Bitmap](https://user-images.githubusercontent.com/392513/103424441-391f3b80-4ba4-11eb-9556-9d5e16cc6e0c.png)


The best advice would be probably to find a proper designer who could help out with such simple things. If you (like me) are used to high quality and well designed apps, seeing Vikunja and its UX, I just get the feeling that the app is not that great because of its poor UX, inconsistent behaviour, and presentation. And this is really easy to change (that feeling) because it all comes down to some css changes and maybe a bit of javascript :-)

Let me know if you have any specific questions or would like to discuss more.

**Comment by kolaente** [comment]
Whoa, thanks for the in-depth answer! I've added most of it to the public backlog (llamas, color usage, animation, inconsistency of components/elements, alignment, button variations) with some comments below.

I think most of these inconsistencies come from the issue that these features grew organically over time without proper guardrails in place. And with each feature I had a new fancy idea of how to implement it ux-wise... which is not the best approach.

> Firstly, please bear in mind that this repo contains my own "database" of apps (which I moved to github from my personal wiki), so these comments are only my personal PoV and aimed at (primarily) myself. I didn't want to offend or criticise anyone, it's just - mainly - my personal preference. I'm also not a designer (albeit have been working in UI/UX dev for the past 20yrs), so I'll keep my comments & remarks below to the point and without a "personal preference" or "feeling" (like a designer might give you), as usage of a particular colour palette, animations, layouts or typography usually depends a lot on the person designing them. I'll focus on the usability, accessibility and general UX best practices.

I'm no designer either hence the design issues with Vikunja :) I mainly try to get feedback however I can since I've made good experience with that. The only way to figure out how users use the app or what "impression" it left them is to talk to them.

> "Create namespace" screen changes the whole bg colour to laser-purple). That's not something you'd see in this type of an application (maybe more in music/video or other game-like apps, here it just looks unprofessional).

That's a leftover from the very first version of Vikunja's design where the rest of the app was styled accordingly. Somehow that has escaped my refactoring efforts. I plan on fixing this soon.

> The contrast ration in some parts if the UI is very low (especially highlighted elements background is not different enough from the non-highlighted background).

In the menu?

> Namespaces idea is fine, albeit maybe it should not be enforced so much

I've been thinking of decoupling lists and namespaces more so that namespaces would work more like "folders" where you can put lists in - as some form of organizing it better, but optionally. I've yet to find a good solution for that and I kind of put it off since that will require a big refactoring effort.

> When I start the app with no data - I land on the overview page and see "Nothing to do - Have a nice day!", with no buttons or info what to do next...

If migration is enabled, it shows a button "hey do you want to migrate your data from other places?" but I agree that some other explanation of simply how to create a new task/list/namespace would be a good idea.

> e.g. List edit screen is probably the most confusing

I agree with that. This is one of these cases where the thing has grown over time and needs some serious refactor. I think moving each "sub form" of the settings to a separate screen which would then be accessible through a dropdown could solve this.

> It's showing elements, that have no data (Share links table only shows table headers, when it's not shared which looks odd)

That sounds like a bug.

> Some actions (like creating a list, removing a namespace) are not applied without reloading the browser (bug?) which is confusing

Same here, sounds like a bug. It looks like adding/removing a list is reflected in the menu, whereas removing a namespace is not.

**Comment by tborychowski** [comment]
No problem. I've been in your shoes too many times myself over the years 😃 
And I know the pain of developing an app for the public. Nowadays I'd like to take as much time as it's needed to refactor, and not adding any more features until my project is in a good state. 

Anyway, if you do the refactoring and need some more feedback give me a shout 😉 
I'll be happy to help.

**Comment by kolaente** [comment]
> Anyway, if you do the refactoring and need some more feedback give me a shout 

Thanks, will do! :grinning:

**Comment by kolaente** [comment]
I've done quite a bit of refactoring of the frontend and then completely forgot about this issue :upside_down_face: 

Would you mind checking again? [The demo](https://try.vikunja.io) is on the latest version.

**Comment by tborychowski** [comment]
Brilliant work! Looks 1000 times better! Don't have time now to set it up locally, but the demo looks very nice! I will update the comment now :-)

**Comment by kolaente** [comment]
Glad to hear!
