### ISSUE TITLE
Auto tagging feature in photo comparison chart

### ISSUE THREAD

**Issue by twiclo** [tborychowski/self-hosted-cookbook#9]
The main thing I look for out of a photo solution is the ability to auto tag images so everything is searchable without me having to do anything. I would love to see that as a column on the comparison chart if possible

**Comment by tborychowski** [comment]
Haha, I'm afraid it doesn't work that way.

This is my repo, for my personal purpose. I'm very happy if someone finds it useful, but I'm not gonna do any additional work for people for free (especially nowadays, where my time is scarce).
I'm happy to review & merge a PR if you want to create one, but nothing more 😄 

If you really want this, and are willing to pay - no problem, I can do it for you: my hourly rate is ~€200, this shouldn't take more than 2h, donation links are under the "Sponsor" button on top of the page.

Otherwise, I'm afraid you have to do it yourself (or find someone else) 😉

**Comment by twiclo** [comment]
Didn't need to be an ass about it

**Comment by tborychowski** [comment]
These were just facts. Explained clearly and politely. If you read more from that, than it's your problem ;-)
